README: Update install/uninstall commands
Got an error:

    error: failed to open: /usr/local/.crates.toml

when I tried the command with the `--root /usr/local` argument, so
decided to remove it.

Need to use the root crate name in the `cargo uninstall` command.